export const ATTACK = {
    RADIUS: 16,
    SHOOT_INTERVAL: 0.25,
    BLEND_SPEED: 2.0,
    WEAPON_TAKEOUT_ANIM_SPEED: 2,
    LOOP_SHOOT_ANIM_SPEED: 1.4,
    DIR_ANIM_SPEED: 1.5,
    DIRECTION_THRESHOLD: 0.5,
    PISTOL_SHOOT_WEIGHT: 0.45,
    OVERLAY_WEIGHT: 1,
    OVERLAY_FADE: 0.1,
    DIR_BLEND_FADE: 0.15,
    TAKEOUT_FADE: 0.01,
} as const;
