export const MOVEMENT = {
    NEAR_ZERO_THRESHOLD: 0.01,
    VELOCITY_THRESHOLD: 0.1,
    DIRECTION_REVERSAL_DOT: -0.5,
    DIRECTION_REVERSAL_DAMPING: 0.2,
    FINAL_STOP_THRESHOLD: 0.05,
} as const;
