export const PLAYER = {
    SPEED: 5,
    ROTATION_SPEED: 25,
    ACCELERATION: 20,
    DECELERATION: 40,
    VISUAL_LERP_SPEED: 20,
    DETECTION_RING_INNER_RADIUS: 6.0,
    DETECTION_RING_OUTER_RADIUS: 6.1,
    DETECTION_RING_SEGMENTS: 48,
    DETECTION_RING_OPACITY: 0.5,
    DETECTION_RING_Y_OFFSET: 0.05,
    DETECTION_RING_PULSE_AMPLITUDE: 0.1,
    DETECTION_RING_PULSE_FREQUENCY: 6,
} as const;
